Formulario_BD/Models/ErrorViewModel.cs
using System;

namespace Formulario_BD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Formulario_BD/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Formulario_BD.Models
{
    public class Persona
    {
        [Key]
        public int idPersona { get; set; }

        [Required]
        public string nombre{ get; set; }
        public float peso { get; set; }
    }
}

Formulario_BD/Models/PersonaContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Formulario_BD.Models
{
    public class PersonaContext : DbContext
    {

        public PersonaContext(DbContextOptions<PersonaContext> opcion):base(opcion)
        {

        }

        public DbSet<Persona> Personas { get; set; }
    }
}

Formulario_BD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Formulario_BD.Models;

namespace Formulario_BD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Formulario_BD/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Formulario_BD.Models;
using Microsoft.AspNetCore.Mvc;

namespace Formulario_BD.Controllers
{
    public class PersonaController : Controller
    {

        private readonly PersonaContext Db;


        public PersonaController(PersonaContext obj)
        {
            Db = obj;
        }

        public IActionResult Index()
        {
           
            return View();
        }

      
        //LA Primera Vez que entra para registrar
        [HttpGet]
        public IActionResult Agregar()
        {
            return View();
        }

        //una ya una vez enviado los datos
        [HttpPost]
        public IActionResult Agregar(Persona p) 
        {
            Db.Add(p);
            Db.SaveChanges();

            ViewBag.valor = 1;
           // return RedirectToAction("Home/Index");
            return View();
        }
    }
}

Formulario_BD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Formulario_BD/Views/Persona/Agregar.cshtml
@model Formulario_BD.Models.Persona


@{
    ViewData["Title"] = "Agregar";

}



<h1>Agregar</h1>

<h4>Persona</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Agregar" asp-controller="Persona">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!--
            <div class="form-group">
                <label asp-for="idPersona" class="control-label"></label>
                <input asp-for="idPersona" class="form-control" />
                <span asp-validation-for="idPersona" class="text-danger"></span>
            </div>
                -->
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="peso" class="control-label"></label>
                <input asp-for="peso" class="form-control" />
                <span asp-validation-for="peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<script
    if (@ViewBag.valor> 0) {
        toastr.info('Are you the 6 fingered man?');
    }
    else {
        toastr.info('Else?');
    }
</script>


<div>
    <a asp-action="Index">Back to List</a>
</div>



    


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Formulario_BD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formulario_BD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Toasts-->
    <link href="toastr.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Formulario_BD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="Agregar">Agregar persona</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Formulario_BD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Toast -->
    <script src="toastr.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>